spring:
  application:
    name: zuul
server:
  port: 8084
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: service-impl
    api-b:
      path: /api-b/**
      serviceId: service-second-impl