spring:
  application:
    name: test-web
server:
  port: 8088
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
  instance:
    #status-page-url: http://localhost:${server.port}/swagger-ui.html
    status-page-url: http://localhost:${server.port}/swagger/index.html
#feign远程调用配置开启熔断
feign:
  hystrix:
    enabled: true
#路由设置
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: service-impl
    api-b:
      path: /api-b/**
      serviceId: service-second-impl
