eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
  instance:
      status-page-url: http://localhost:${server.port}/swagger-ui.html
server:
  port: 8083
spring:
  application:
    name: test-web