spring:
  application:
    name: service-impl
server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
info:
  app:
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"
    #spring-boot-version: "@project.parent.version@"