spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          # 配置git仓库的地址
          uri: https://github.com/huanyingtoyou/springCloud/
          # git仓库地址下的相对地址，可以配置多个，用,分割
          search-paths: config-repository
          # git仓库的账号
          username: lihy
          # git仓库的密码
          password: 123456
server:
  port: 8085
eureka:
  client:
    serviceUrl:
      # 注册中心eureka地址
      defaultZone: http://localhost:8081/eureka/