spring:
  application:
    name: service-second-impl
server:
  port: 8083
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
info:
  app:
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"